<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\environment.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Exploration</RootNamespace>
    <AssemblyName>Exploration</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BEPINEX_PATH)\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BEPINEX_PATH)\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(VALHEIM_MANAGED)\publicized_assemblies\assembly_valheim_publicized.dll</HintPath>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>$(VALHEIM_MANAGED)\publicized_assemblies\assembly_guiutils_publicized.dll</HintPath>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(VALHEIM_MANAGED)\publicized_assemblies\assembly_utils_publicized.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(VALHEIM_MANAGED)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(VALHEIM_MANAGED)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(VALHEIM_MANAGED)\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="Splatform">
      <HintPath>$(VALHEIM_MANAGED)\Splatform.dll</HintPath>
    </Reference>
    <Reference Include="ServerSync">
      <HintPath>ServerSync.dll</HintPath>
    </Reference>
    <Reference Include="SkillManager">
      <HintPath>SkillManager.dll</HintPath>
    </Reference>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\icons\exploration.png" LogicalName="Exploration.icons.exploration.png" />
    <EmbeddedResource Include="..\icons\burial.png" LogicalName="Exploration.icons.burial.png" />
    <EmbeddedResource Include="..\icons\troll_cave.png" LogicalName="Exploration.icons.troll_cave.png" />
    <EmbeddedResource Include="..\icons\mountain_cave.png" LogicalName="Exploration.icons.mountain_cave.png" />
    <EmbeddedResource Include="..\icons\mistland_dungeon.png" LogicalName="Exploration.icons.mistland_dungeon.png" />
    <EmbeddedResource Include="..\icons\mistland_dungeon_rock.png" LogicalName="Exploration.icons.mistland_dungeon_rock.png" />
    <EmbeddedResource Include="..\icons\morgen_hole.png" LogicalName="Exploration.icons.morgen_hole.png" />
    <EmbeddedResource Include="..\icons\oremine.png" LogicalName="Exploration.icons.oremine.png" />
    <EmbeddedResource Include="..\icons\crypt.png" LogicalName="Exploration.icons.crypt.png" />
  </ItemGroup>
  <Target Name="CopyPlugins" AfterTargets="ILRepack">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MOD_DEPLOYPATH)\$(AssemblyName)" SkipUnchangedFiles="true" />
  </Target>
</Project>
